name: UncraftingTable
version: '1.1'
main: com.ashkiano.uncraftingtable.UncraftingTable
api-version: '1.16'
author: AshKiano
commands:
  uncrafting:
    description: Opens uncrafting table
    usage: /<command>